import assert from 'node:assert/strict'
import fs from 'node:fs'

function read(file: string) {
  return fs.readFileSync(file, 'utf8')
}

const opsRoute = read('app/api/ops/desktop-activation/route.ts')
const opsPage = read('app/ops/desktop/activation/page.tsx')
const opsHome = read('app/ops/page.tsx')
const desktopPinRoute = read('app/api/desktop/activation-pins/route.ts')
const pinIssuance = read('lib/desktop-activation/pin-issuance.ts')

assert.match(opsRoute, /checkOpsAuthContext/, 'ops PIN API must use server-side ops auth')
assert.match(opsRoute, /hasOpsRole\(ops\.role,\s*'OPS_ADMIN'\)/, 'ops PIN API must require OPS_ADMIN or higher')
assert.doesNotMatch(opsRoute, /getContext\(/, 'ops PIN API must not authorize as a merchant OWNER')
assert.doesNotMatch(opsRoute, /NextResponse\.json/, 'ops PIN API must use noStoreJson/apiError')
assert.match(opsRoute, /noStoreJson|apiError/, 'ops PIN API responses must be no-store')
assert.match(opsRoute, /issueDesktopActivationPin/, 'ops PIN API must delegate issuance to the shared 06A service')
assert.match(opsRoute, /STORE_CODE_PATTERN/, 'ops PIN API must reject malformed storeCode values')
assert.match(opsRoute, /createdByUserId:\s*null/, 'ops PIN API must not attribute ops-issued PINs to merchant users')
assert.match(opsRoute, /createdByOpsAdminId:\s*auth\.ops\.userId/, 'ops PIN API must persist verified OpsAdmin creator id')
assert.match(opsRoute, /actorOpsAdminId:\s*auth\.ops\.userId/, 'ops PIN API must persist verified OpsAdmin audit actor id')
assert.match(opsRoute, /operatorRole:\s*auth\.ops\.role/, 'ops PIN API must derive operator role from verified session')
assert.doesNotMatch(opsRoute, /body\.(createdBy|actor|operator)/, 'ops PIN API must ignore client-supplied actor fields')
assert.match(opsRoute, /auditReasonCode:\s*'OPS_ISSUED'/, 'ops-issued PINs should be marked in desktop activation audit reasonCode')
assert.doesNotMatch(opsRoute, /deviceToken|tokenHash|pinHash|installationIdHash/, 'ops PIN API must not return device tokens or internal hashes')

assert.match(pinIssuance, /createActivationPin\(\)/, 'shared issuance service must own PIN creation')
assert.match(pinIssuance, /hashActivationPin/, 'shared issuance service must hash PINs before persistence')
assert.match(pinIssuance, /createdByUserId:\s*input\.createdByUserId/, 'shared issuance service must persist merchant creator when provided')
assert.match(pinIssuance, /createdByOpsAdminId:\s*input\.createdByOpsAdminId/, 'shared issuance service must persist ops creator when provided')
assert.match(pinIssuance, /actorOpsAdminId:\s*input\.actorOpsAdminId/, 'shared issuance service must persist ops audit actor when provided')
assert.match(pinIssuance, /exactlyOne\(input\.createdByUserId,\s*input\.createdByOpsAdminId\)/, 'shared issuance service must enforce exactly one creator')
assert.match(pinIssuance, /updateMany\(\{[\s\S]*status:\s*'REVOKED'[\s\S]*activeSlot:\s*null/, 'new PIN issuance must revoke any existing active PIN')
assert.match(pinIssuance, /writeDesktopActivationAudit[\s\S]*eventType:\s*'PIN_CREATED'/, 'new PIN issuance must write PIN_CREATED audit')
assert.match(pinIssuance, /writeDesktopActivationAudit[\s\S]*eventType:\s*'PIN_CREATE_DENIED'/, 'subscription-denied issuance must be audited')
assert.doesNotMatch(pinIssuance, /console\.|OperationLog|payloadSnapshot/, 'shared issuance service must not log PIN material')

assert.match(desktopPinRoute, /issueDesktopActivationPin/, 'existing merchant PIN route should reuse shared issuance service')
assert.doesNotMatch(desktopPinRoute, /createActivationPin|hashActivationPin|DESKTOP_ACTIVATION_PIN_HASH_VERSION/, 'existing merchant PIN route must not duplicate PIN issuance internals')
assert.match(desktopPinRoute, /createdByUserId:\s*ctx\.userId/, 'merchant PIN route must keep merchant creator attribution')
assert.match(desktopPinRoute, /createdByOpsAdminId:\s*null/, 'merchant PIN route must not set ops creator attribution')
assert.match(desktopPinRoute, /actorUserId:\s*ctx\.userId/, 'merchant PIN route must keep merchant audit actor attribution')

assert.match(opsPage, /\/api\/ops\/desktop-activation/, 'ops page must call the ops PIN API')
assert.match(opsPage, /navigator\.clipboard\.writeText\(issued\.pin\)/, 'copy must be an explicit user-triggered action')
assert.doesNotMatch(opsPage, /localStorage|sessionStorage|console\./, 'ops page must not persist or log PINs')
assert.doesNotMatch(opsPage, /params\.set\(['"]pin|router\.push[\s\S]*issued\.pin|window\.location[\s\S]*issued\.pin/, 'ops page must not put PIN state in the URL')
assert.match(opsPage, /setIssued\(null\)/, 'ops page must clear one-time PIN state when changing context')
assert.match(opsPage, /confirmStore/, 'ops page must use page-level issuance confirmation state')
assert.match(opsPage, /Generate Activation PIN/, 'ops page must show an explicit issuance confirmation title')
assert.match(opsPage, /当前有效 PIN 将立即失效。/, 'ops page must warn that an active PIN is invalidated')
assert.doesNotMatch(opsPage, /\bconfirm\(/, 'ops page must not rely on native browser confirm')
assert.match(opsPage, /Reference:/, 'ops page may show a safe reference code after user-friendly text')

const schema = read('prisma/schema.prisma')
const migration = read('prisma/migrations/20260719090000_model_activation_pin_ops_attribution/migration.sql')
assert.match(schema, /createdByOpsAdminId String\?/, 'schema must add explicit ops creator field')
assert.match(schema, /actorOpsAdminId\s+String\?/, 'schema must add explicit ops audit actor field')
assert.match(schema, /createdByOpsAdmin OpsAdmin\?[\s\S]*onDelete: SetNull/, 'ops creator relation must SetNull on delete')
assert.match(schema, /actorOpsAdmin OpsAdmin\?[\s\S]*onDelete: SetNull/, 'ops audit actor relation must SetNull on delete')
assert.match(schema, /@@index\(\[createdByOpsAdminId\]\)/, 'schema must index ops creator field')
assert.match(schema, /@@index\(\[actorOpsAdminId\]\)/, 'schema must index ops audit actor field')
assert.match(migration, /DesktopActivationPin_exactly_one_creator_check/, 'migration must enforce exactly one PIN creator')
assert.match(migration, /ALTER COLUMN "createdByUserId" DROP NOT NULL/, 'migration must preserve historical user creator while allowing ops creator')

assert.match(opsHome, /href="\/ops\/desktop\/activation"/, 'ops home should link to the productized Desktop console')

console.log('desktop activation PIN console static tests passed')
