import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync(new URL('../app/qz-print-test/page.tsx', import.meta.url), 'utf8')
const client = readFileSync(new URL('../app/qz-print-test/QzPrintTestClient.tsx', import.meta.url), 'utf8')
const layout = readFileSync(new URL('../app/layout.tsx', import.meta.url), 'utf8')

assert.match(page, /process\.env\.VERCEL_ENV === 'preview'/)
assert.match(page, /QZ-PRINT-02C/)
assert.match(page, /NEXT_PUBLIC_QZ_PRINT_PREVIEW_COMMIT/)
assert.match(page, /\^\[0-9a-f\]\{40\}\$/)
assert.match(page, /notFound\(\)/)

assert.match(layout, /isQzPrintTestPath \? children/)
assert.match(client, /data-qz-print-test-page="QZ-PRINT-02C"/)
assert.match(client, /Commit: \{previewCommit\}/)
assert.match(client, /Environment: Preview/)
assert.match(client, /Mode: ESC \* 0x21 \/ ESC d 3 \/ GS V 0 \/ QZ RAW/)
assert.match(client, /data-qz-status=/)
assert.match(client, /data-qz-printer-list/)
assert.match(client, /正式顾客票 RAW → 前台/)
assert.match(client, /正式厨房票 RAW → 厨房/)
assert.match(client, /data-qz-formal-raw-action=/)
assert.match(client, /printCustomerReceiptViaQz\(renderDesktopReceiptHtml\(customerTestReceipt\(\), 'zh'\)\)/)
assert.match(client, /printKitchenTicketViaQz\(renderKitchenTicketHtml\(kitchenTestTicket\(\), 'zh'\)\)/)
assert.match(client, /formalRawInFlight\.current\.has\(kind\)/)
assert.match(client, /A｜顾客票 → 前台/)
assert.match(client, /B｜顾客票 → 厨房/)
assert.match(client, /C｜厨房票 → 前台/)
assert.match(client, /D｜厨房票 → 厨房/)
assert.match(client, /printHtmlViaFixedQzQueue\(testCase\.queueKind, html\)/)
assert.match(client, /前台 RAW 位图测试/)
assert.match(client, /厨房 RAW 位图测试/)
assert.match(client, /data-qz-raw-action=/)
assert.match(client, /buildFixedEscPosRawTestImage\(\)/)
assert.match(client, /encodeRgbaToEscPosEscStar24/)
assert.match(client, /printEscPosBitImageViaFixedQzQueue\(kind, bytes\)/)
assert.match(client, /rawInFlight\.current\.has\(kind\)/)
assert.match(client, /rawBitmapBytes\.current = buildFixedEscPosRawTestImage\(\)/)
assert.match(client, /FIXED_CREATED_AT = '2026-08-02T00:00:00\.000Z'/)
assert.match(client, /QZ_STATUS_TIMEOUT_MS = 8_000/)
assert.match(client, /qzStatus !== 'online'/)
assert.match(client, /!printers\.includes\(queueName\)/)
assert.doesNotMatch(client, /apiFetch|fetch\(|axios|\/api\//)
assert.doesNotMatch(client, /window\.print|printDesktopReceipt|printKitchenTicket\(/)
assert.doesNotMatch(client, /getDefault|defaultPrinter/i)
assert.doesNotMatch(client, /ComputerBinding|PaymentIntent|SaleRecord|customerId|productId|inventory/)

console.log('QZ standalone print test static checks passed')
