import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

function read(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
}

const adapter = read('lib/qzPrinterAdapter.ts')
const config = read('lib/qz-signing-config.ts')
const server = read('lib/qz-signing-server.ts')
const signingRoute = read('lib/qz-signing-route.ts')
const configRoute = read('app/api/qz/config/route.ts')
const signRoute = read('app/api/qz/sign/route.ts')
const cashier = read('app/cashier/page.tsx')

assert.match(adapter, /setSignatureAlgorithm\('SHA512'\)/)
assert.match(adapter, /setCertificatePromise[\s\S]*rejectOnFailure:\s*true/)
assert.match(adapter, /fetch\('\/api\/qz\/config'/)
assert.match(adapter, /fetch\('\/api\/qz\/sign'/)
assert.match(adapter, /'Content-Type':\s*'text\/plain; charset=utf-8'/)
assert.match(adapter, /'X-QZ-Certificate-Version':\s*securityConfig\.certificateVersion/)
assert.match(adapter, /posDeviceHeaders\(currentCashierStoreCode\(\)\)/)
assert.match(adapter, /clearQzSecurityConfigForRecovery/)
assert.match(adapter, /qzSecurityConfigPromise === pending/)
assert.match(adapter, /QZ_SECURITY_UNAVAILABLE/)
assert.doesNotMatch(adapter, /resolve\(''\)/, 'blank QZ certificate/signature fallback must be removed')
assert.doesNotMatch(adapter, /window\.print/, 'QZ signing failures must not downgrade to browser printing')
assert.match(cashier, /安全签名服务不可用，票据未发送/)

assert.match(configRoute, /certificate:\s*config\.certificate/)
assert.match(configRoute, /signatureAlgorithm:\s*config\.signatureAlgorithm/)
assert.match(configRoute, /certificateVersion:\s*config\.certificateVersion/)
assert.match(configRoute, /enabled:\s*config\.mode !== 'disabled'/)
assert.match(configRoute, /Cache-Control':\s*'no-store/)
assert.doesNotMatch(configRoute, /verifyPosDevice|getContext|ComputerBinding/, 'public QZ config must not require a POS session')

assert.match(signRoute, /handleQzSignRequest\(req\)/)
assert.match(signingRoute, /assertQzSignOrigin\(req, config\)/)
assert.match(signingRoute, /assertQzSignContentType\(req\)/)
assert.match(signingRoute, /assertQzCertificateVersion\(req, config\)/)
assert.match(signingRoute, /assertQzDigestText\(await req\.text\(\)\)/)
assert.match(signingRoute, /dependencies\.verifySession\(req\)/)
assert.match(signingRoute, /isQzSigningStoreAllowed\(config, session\.storeCode\)/)
assert.match(signingRoute, /dependencies\.reserveAttempt/)
assert.match(signingRoute, /dependencies\.sign/)
assert.match(signingRoute, /dependencies\.finishAudit/)
assert.doesNotMatch(signingRoute, /ComputerBinding|window\.print|application\/json[\s\S]*req\.json/)

assert.match(config, /'disabled' \| 'canary' \| 'general'/)
assert.match(config, /mode === 'canary' && values\.length === 0/)
assert.match(config, /mode === 'general' && values\.length > 0/)
assert.match(config, /if \(config\.mode === 'general'\) return true/)
assert.match(config, /new X509Certificate/)
assert.match(config, /fingerprint !== expectedSha256/)
assert.match(config, /versionPairs:\s*ReadonlyMap/)
assert.match(config, /signingEnabled/)

assert.match(server, /verifyPosDeviceRequest/)
assert.match(server, /payload\?\.browserPosSessionId/)
assert.doesNotMatch(server, /computerBinding|claimSecret|deviceSecret/i)
assert.match(server, /Prisma\.TransactionIsolationLevel\.Serializable/)
assert.match(server, /actionType:\s*'QZ_SIGN'/)
assert.match(server, /deviceHash/)
assert.match(server, /ipHash/)
assert.match(server, /storeAttempts/)
assert.doesNotMatch(server, /digestText[,}]\s*\n?\s*payloadSnapshot|Signature[,:]\s*.*payloadSnapshot/)
assert.match(server, /Message:\s*Buffer\.from\(assertQzDigestText\(digestText\), 'utf8'\)/)
assert.match(server, /MessageType:\s*QZ_KMS_MESSAGE_TYPE/)
assert.match(server, /SigningAlgorithm:\s*QZ_KMS_SIGNING_ALGORITHM/)
assert.match(server, /verifySignature\('RSA-SHA512'/)
assert.match(server, /awsCredentialsProvider/)
assert.doesNotMatch(server, /fromHex|hexTo|Buffer\.from\([^)]*,\s*'hex'\)|MessageType:\s*['"]DIGEST/)
assert.doesNotMatch(server, /PRIVATE KEY|private-key|\.pfx|\.pem/i)

console.log('QZ signing static checks passed')
