import assert from 'node:assert/strict'
import fs from 'node:fs'

const opsAuth = fs.readFileSync('lib/ops-auth.ts', 'utf8')
const blockRoute = fs.readFileSync('app/api/ops/sales-leads/[id]/block/route.ts', 'utf8')
const rejectRoute = fs.readFileSync('app/api/ops/applications/[id]/reject/route.ts', 'utf8')
const openRoute = fs.readFileSync('app/api/open/route.ts', 'utf8')
const listRoute = fs.readFileSync('app/api/ops/sales-leads/route.ts', 'utf8')
const detailRoute = fs.readFileSync('app/api/ops/sales-leads/[id]/route.ts', 'utf8')
const webhook = fs.readFileSync('app/api/webhook/merchant/route.ts', 'utf8')
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')

assert.match(opsAuth, /getFkBackedOpsAdminIdentity/)
assert.match(opsAuth, /context\.userId === '_ops_admin'/)
assert.match(opsAuth, /prisma\.opsAdmin\.findUnique/)
assert.match(opsAuth, /admin\.status !== 'ACTIVE'/)
assert.match(opsAuth, /admin\.role !== 'SUPER_ADMIN' && admin\.role !== 'OPS_ADMIN'/)
assert.match(blockRoute, /getFkBackedOpsAdminIdentity\(req, 'OPS_ADMIN'\)/)
assert.match(blockRoute, /action !== 'BAN' && action !== 'UNBAN'/)
assert.match(blockRoute, /unblockedByOpsAdminId: actor\.id/)
assert.match(blockRoute, /pg_advisory_xact_lock/)
assert.match(rejectRoute, /status: 'REJECTED'/)
assert.match(rejectRoute, /const ban = body\?\.ban === true/)
assert.match(rejectRoute, /BAN_FORBIDDEN/)
assert.match(rejectRoute, /where: \{ id, status: 'PENDING' \}/)
assert.match(openRoute, /activeApplicationBlock/)
assert.match(openRoute, /status: 'PENDING'/)
assert.match(openRoute, /getSalesLeadTelegramAdvisoryKey/)
assert.match(listRoute, /visitCount/)
assert.match(listRoute, /validLeads/)
assert.doesNotMatch(listRoute, /uniqueVisitors/i)
assert.match(detailRoute, /conversationUrl/)
assert.doesNotMatch(webhook, /applicationBlock/)
assert.doesNotMatch(schema, /model SalesChat|model SalesMessage/)
assert.doesNotMatch(schema, /salesLeadId\s+String\?\s+@unique/)

console.log('sales lead ops guard tests passed')
