import assert from 'node:assert/strict'
import fs from 'node:fs'

const auth = fs.readFileSync('lib/sales-workspace-auth.ts', 'utf8')
const list = fs.readFileSync('app/api/sales/leads/route.ts', 'utf8')
const claim = fs.readFileSync('app/api/sales/leads/[id]/claim/route.ts', 'utf8')
const status = fs.readFileSync('app/api/sales/leads/[id]/route.ts', 'utf8')
const conversations = fs.readFileSync('app/api/sales/conversations/route.ts', 'utf8')
const messages = fs.readFileSync('app/api/sales/messages/route.ts', 'utf8')
const inquiries = fs.readFileSync('app/api/sales/inquiries/route.ts', 'utf8')
const page = fs.readFileSync('app/ops/sales/page.tsx', 'utf8')

assert.match(auth, /checkOpsAuthContext/)
assert.match(auth, /context\.role === 'OPS_ADMIN' \|\| context\.role === 'SUPER_ADMIN'/)
assert.match(list, /const currentOwnerWhere:[\s\S]+salesOwnerId: actor\.userId/)
assert.match(list, /initialSalesOwnerId: actor\.userId/)
assert.match(list, /const unassignedWhere:[\s\S]*salesOwnerId: null/)
assert.match(list, /const query = \(req\.nextUrl\.searchParams\.get\('q'\)/)
assert.match(list, /normalizedPhone: \{ contains: query \}/)
assert.match(list, /telegramUsername: \{ contains: query/)
assert.match(list, /Unassigned Lead search intentionally excludes owner\/phone\/Telegram fields/)
assert.match(list, /unassigned: unassigned\.map/)
assert.doesNotMatch(list.slice(list.indexOf('unassigned: unassigned.map')), /ownerName: lead\.ownerName|phone: lead\.normalizedPhone/)
assert.match(claim, /where: \{ id, salesOwnerId: null \}/)
assert.doesNotMatch(claim, /initialSalesOwnerId/)
assert.match(status, /canAccessOwnedSalesLead/)
assert.match(status, /notIn: \['APPLIED', 'ACTIVATED'\]/)
assert.match(conversations, /channel: 'SALES_ONBOARDING', salesLeadId/)
assert.match(messages, /channel: 'SALES_ONBOARDING'/)
assert.match(messages, /select: \{ recipientTelegramId: true \}/)
assert.doesNotMatch(messages, /body\?\.recipientTelegramId|recipientTelegramId\?: unknown/)
assert.match(messages, /SALES_ONBOARDING_BOT_TOKEN/)
assert.match(inquiries, /salesInquiryOwnerId/)
assert.match(inquiries, /salesInquiryOwnerId: null/)
assert.match(inquiries, /ALREADY_CLAIMED/)
assert.match(inquiries, /actor\.isManager/)
assert.match(page, /\/api\/sales\/leads/)
assert.match(page, /\/api\/sales\/inquiries/)
assert.match(page, /salesWorkspace\.unlinkedInquiries/)
assert.match(page, /sales-shell/)
assert.match(page, /grid-template-columns:minmax\(180px,220px\) minmax\(300px,370px\)/)
assert.match(page, /setLang\(option\.code\)/)
assert.match(page, /salesWorkspace\.telegramUsername/)
assert.match(page, /@media\(max-width:360px\)/)
assert.match(page, /\/api\/sales\/messages/)
assert.doesNotMatch(page, /\/api\/ops\/store-applications|rejectApplication|banApplication|unbanApplication/i)

console.log('sales workspace tests passed')
