const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = (value) => fs.readFileSync(path.join(root, value), 'utf8')

test('V3 control plane schema is dedicated, store-scoped and device-scope fenced', () => {
  const schema = read('prisma/schema.prisma')
  assert.match(schema, /model V3PrintControlPlane \{/)
  assert.match(schema, /storeId\s+String\s+@unique/)
  assert.match(schema, /ownerEpoch\s+Int\s+@default\(0\)/)
  assert.match(schema, /ownerDevice DesktopDevice\?\s+@relation\("V3PrintControlPlaneOwner", fields: \[ownerDeviceId, tenantId, storeId\]/)
  assert.match(schema, /model V3PrintExecutionBatch \{/)
  assert.match(schema, /ownerDevice\s+DesktopDevice\s+@relation\("V3PrintExecutionBatchOwner", fields: \[ownerDeviceId, tenantId, storeId\]/)
})

test('migration constrains mode, owner shape, expiry and exact composite identity', () => {
  const sql = read('prisma/migrations/20260923022000_add_v3_print_control_plane/migration.sql')
  assert.match(sql, /mode_check.*V2_ACTIVE.*V2_DRAINING.*V3_ACTIVE.*V3_DRAINING.*BLOCKED_UNKNOWN/s)
  assert.match(sql, /owner_shape_check/)
  assert.match(sql, /V3PrintExecutionBatch_expiry_check/)
  assert.match(sql, /FOREIGN KEY \("ownerDeviceId", "tenantId", "storeId"\) REFERENCES "DesktopDevice"\("id", "tenantId", "storeId"\)/)
})

test('server writer rejects timeout promotion and requires explicit fenced writes', () => {
  const source = read('lib/v3-print-control-plane.ts')
  assert.match(source, /OWNER_LIVENESS_AMBIGUOUS/)
  assert.doesNotMatch(source, /leaseExpiresAt:\s*\{\s*lte: now\s*\}.*ownerEpoch:\s*\{\s*increment/s)
  assert.match(source, /stateVersion: identity\.stateVersion/)
  assert.match(source, /leaseExpiresAt: \{ gt: now \}/)
  assert.match(source, /controlledV3OwnerHandoff/)
})

test('Desktop and Owner APIs keep authority roles separate and retire raw OWNER mode writes', () => {
  const desktop = read('app/api/desktop/v3-print-control-plane/route.ts')
  const owner = read('app/api/owner/v3-print-control-plane/route.ts')
  assert.match(desktop, /getDesktopDeviceContext/)
  assert.doesNotMatch(desktop, /transitionV3PrintMode|controlledV3OwnerHandoff/)
  assert.match(owner, /ctx\.role !== 'OWNER'/)
  assert.match(owner, /body\.action === 'SET_MODE'/)
  assert.match(owner, /RAW_SET_MODE_RETIRED/)
  assert.match(owner, /status: 409/)
  assert.doesNotMatch(owner, /transitionV3PrintMode|V3_PRINT_MODES/)
  assert.match(owner, /controlledV3OwnerHandoff/)
})

test('Ops activation adapter is authenticated, store-scoped and service-composed', () => {
  const route = read('app/api/ops/tenants/[tenantId]/stores/[storeId]/v3-print-control-plane/route.ts')
  const service = read('app/api/ops/tenants/[tenantId]/stores/[storeId]/v3-print-control-plane/service.ts')
  assert.match(route, /getFkBackedOpsAdminIdentity\(request, 'OPS_ADMIN'\)/)
  assert.match(route, /where: \{ id: storeId, tenantId, status: 'ACTIVE' \}/)
  assert.match(route, /resolveOpsPrintStoreAccess/)
  assert.match(route, /parseOpsPrintModeCommand/)
  assert.match(route, /validateOpsPrintMutationRequest/)
  assert.match(service, /'tenantId' in input \|\| 'storeId' in input \|\| 'ownerDeviceId' in input/)
  assert.match(service, /transitionV3PrintMode/)
  assert.match(service, /START_ACTIVATION[\s\S]*nextMode: 'V2_DRAINING'/)
  assert.match(service, /ENTER_MANUAL_REVIEW[\s\S]*nextMode: 'BLOCKED_UNKNOWN'/)
  assert.match(service, /FINALIZE_V3_ACTIVE[\s\S]*nextMode: 'V3_ACTIVE'/)
  assert.match(service, /START_DEACTIVATION[\s\S]*nextMode: 'V3_DRAINING'/)
  assert.match(service, /FINALIZE_V2_ACTIVE[\s\S]*nextMode: 'V2_ACTIVE'/)
  assert.match(service, /expectedStateVersion: initial\.stateVersion/)
  assert.match(service, /V2_DRAIN_NOT_COMPLETE/)
  assert.match(service, /V3_DRAIN_NOT_COMPLETE/)
  assert.match(service, /V3_EXECUTION_AMBIGUOUS/)
  assert.match(service, /V3_DURABLY_HELD/)
  assert.match(service, /V2_DRAIN_WINDOW_MS = 120_000/)
  assert.match(service, /effectBoundary: 'CROSSING_UNKNOWN'/)
  assert.match(service, /V3_PRINT_MODE_OPERATOR_CONFIRMATION/)
  assert.match(service, /isolationLevel: 'Serializable'/)
  assert.match(service, /throw new RejectedTransition/)
  assert.match(route, /UNEXPECTED_SERVER_ERROR/)
  assert.doesNotMatch(`${route}\n${service}`, /v3PrintControlPlane\.(?:update|updateMany|upsert)\(/)
})

test('Ops merchant detail renders authoritative modes and fail-closed controls', () => {
  const page = read('app/ops/[tenantId]/page.tsx')
  assert.match(page, /打印模式/)
  assert.match(page, /传统打印/)
  assert.match(page, /正在切换到 Local First/)
  assert.match(page, /Local First/)
  assert.match(page, /正在切回传统打印/)
  assert.match(page, /需要人工处理/)
  assert.match(page, /BLOCKED_UNKNOWN 不会自动转出/)
  assert.match(page, /确认启用 Local First/)
  assert.match(page, /确认恢复传统打印/)
  assert.match(page, /expectedStateVersion: state\.controlPlane\.stateVersion/)
  assert.match(page, /if \(!state \|\| loading \|\| error\) return/)
  assert.match(page, /disabled=\{controlsDisabled\}/)
})
