import { createHash, randomUUID } from 'crypto'
import { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import {
  openBrowserPosBindingDelivery,
  sealBrowserPosBindingDelivery,
  type BrowserPosBindingDeliveryContext,
} from '@/lib/browser-pos-binding-delivery'
import {
  issueBrowserPosDeviceInTransaction,
  type BrowserPosStoreScope,
} from '@/lib/browser-pos-device'

export const POS_DEVICE_AUTH_ACTION = 'POS_DEVICE_AUTH_REQUEST'
export const POS_DEVICE_AUTH_TARGET = 'POS_DEVICE'
export const POS_DEVICE_AUTH_SHARED_LINK = 'OWNER_SHARED_LINK'
export const POS_DEVICE_AUTH_QR = 'QR_OWNER_CONFIRMATION'
export const POS_DEVICE_AUTH_TTL_MS = 10 * 60 * 1000
export const POS_DEVICE_DELIVERY_TTL_MS = 5 * 60 * 1000

export type PosAuthorizationPayload = {
  challengeType?: typeof POS_DEVICE_AUTH_SHARED_LINK | typeof POS_DEVICE_AUTH_QR
  expiresAt?: string
  storeCode?: string
  storeName?: string
  deviceName?: string
  approvedAt?: string
  deliveredAt?: string
  boundAt?: string
  browserPosDeviceId?: string
  tokenExpiresAt?: string
  browserInfo?: string
}

type ChallengeFailure = {
  ok: false
  status: 403 | 404 | 409 | 410
  error: 'NOT_FOUND' | 'CHALLENGE_EXPIRED' | 'CHALLENGE_USED' | 'CHALLENGE_NOT_APPROVED' | 'CHALLENGE_TYPE_INVALID' | 'STORE_UNAVAILABLE' | 'ISSUER_UNAVAILABLE' | 'DELIVERY_EXPIRED' | 'DELIVERY_UNAVAILABLE'
}

type ChallengeSuccess<T> = { ok: true } & T

function readPayload(value: unknown): PosAuthorizationPayload {
  return (typeof value === 'object' && value !== null ? value : {}) as PosAuthorizationPayload
}

function cleanText(value: string | null | undefined, maxLength: number) {
  return value?.trim().slice(0, maxLength) || null
}

function challengeType(payload: PosAuthorizationPayload) {
  return payload.challengeType ?? POS_DEVICE_AUTH_QR
}

function isExpired(payload: PosAuthorizationPayload) {
  const expiresAt = payload.expiresAt ? new Date(payload.expiresAt).getTime() : 0
  return !expiresAt || Date.now() > expiresAt
}

function deliveryExpiresAt(payload: PosAuthorizationPayload, now = Date.now()) {
  const challengeExpiry = payload.expiresAt ? new Date(payload.expiresAt).getTime() : 0
  return new Date(Math.min(challengeExpiry, now + POS_DEVICE_DELIVERY_TTL_MS))
}

export function qrBindingAttemptId(requestId: string, deviceId: string) {
  return `qr-${createHash('sha256').update(`${requestId}\0${deviceId}`).digest('base64url')}`
}

async function lockChallenge(tx: Prisma.TransactionClient, requestId: string) {
  const locked = await tx.$queryRaw<Array<{ id: string }>>`
    SELECT "id"
    FROM "OperationLog"
    WHERE "requestId" = ${requestId}
      AND "actionType" = ${POS_DEVICE_AUTH_ACTION}
      AND "targetType" = ${POS_DEVICE_AUTH_TARGET}
    ORDER BY "createdAt" DESC
    LIMIT 1
    FOR UPDATE
  `
  if (!locked[0]) return null
  return tx.operationLog.findUnique({ where: { id: locked[0].id } })
}

async function resolveActiveStoreAndIssuer(
  tx: Prisma.TransactionClient,
  input: { tenantId: string; storeId: string | null; issuerUserId: string | null },
) {
  if (!input.storeId || !input.issuerUserId) return { ok: false as const, error: 'ISSUER_UNAVAILABLE' as const }
  const store = await tx.store.findFirst({
    where: {
      id: input.storeId,
      tenantId: input.tenantId,
      status: 'ACTIVE',
      tenant: { status: 'ACTIVE' },
    },
    select: { id: true, tenantId: true, code: true, name: true },
  })
  if (!store) return { ok: false as const, error: 'STORE_UNAVAILABLE' as const }
  const issuer = await tx.userStoreRole.findFirst({
    where: {
      tenantId: input.tenantId,
      storeId: store.id,
      userId: input.issuerUserId,
      role: 'OWNER',
      status: 'ACTIVE',
      user: { status: 'ACTIVE' },
    },
    select: { userId: true },
  })
  if (!issuer) return { ok: false as const, error: 'ISSUER_UNAVAILABLE' as const }
  return { ok: true as const, store, issuerUserId: issuer.userId }
}

/** Creates the owner-originated, one-time browser binding capability. */
export async function createBrowserPosSharedLink(input: BrowserPosStoreScope & {
  issuedByUserId: string
  storeName: string
}) {
  const requestId = randomUUID()
  const expiresAt = new Date(Date.now() + POS_DEVICE_AUTH_TTL_MS)
  await prisma.operationLog.create({
    data: {
      tenantId: input.tenantId,
      storeId: input.storeId,
      userId: input.issuedByUserId,
      actionType: POS_DEVICE_AUTH_ACTION,
      targetType: POS_DEVICE_AUTH_TARGET,
      requestId,
      status: 'FAILED', // FAILED is the legacy storage representation of an unconsumed challenge.
      message: 'Browser POS shared link generated by owner',
      payloadSnapshot: {
        challengeType: POS_DEVICE_AUTH_SHARED_LINK,
        storeCode: input.storeCode,
        storeName: input.storeName,
        expiresAt: expiresAt.toISOString(),
        issuedAt: new Date().toISOString(),
      },
    },
  })
  return { requestId, expiresAt }
}

/**
 * Records an OWNER's approval for the existing QR flow without consuming the
 * challenge. The original requesting browser consumes it later, atomically
 * with BrowserPosDevice issuance, through redeemBrowserPosAuthorization.
 */
export async function approveBrowserPosAuthorization(input: {
  requestId: string
  tenantId: string
  userId: string
  deviceName?: string | null
}) {
  return prisma.$transaction(async (tx): Promise<ChallengeSuccess<{ storeName: string; deviceName: string }> | ChallengeFailure> => {
    const row = await lockChallenge(tx, input.requestId)
    if (!row) return { ok: false, status: 404, error: 'NOT_FOUND' }
    if (row.tenantId !== input.tenantId) return { ok: false, status: 403, error: 'CHALLENGE_TYPE_INVALID' }
    const payload = readPayload(row.payloadSnapshot)
    if (challengeType(payload) !== POS_DEVICE_AUTH_QR) return { ok: false, status: 409, error: 'CHALLENGE_TYPE_INVALID' }
    if (isExpired(payload)) return { ok: false, status: 410, error: 'CHALLENGE_EXPIRED' }
    if (payload.browserPosDeviceId || row.status === 'SUCCESS') return { ok: false, status: 409, error: 'CHALLENGE_USED' }
    if (payload.approvedAt) return { ok: false, status: 409, error: 'CHALLENGE_USED' }

    const active = await resolveActiveStoreAndIssuer(tx, {
      tenantId: row.tenantId,
      storeId: row.storeId,
      issuerUserId: input.userId,
    })
    if (!active.ok) {
      return {
        ok: false,
        status: 403,
        error: active.error,
      }
    }

    const deviceName = cleanText(input.deviceName, 80) ?? payload.deviceName ?? '前台收银机'
    await tx.operationLog.update({
      where: { id: row.id },
      data: {
        userId: active.issuerUserId,
        message: 'Browser POS device approved by owner; awaiting requesting browser redemption',
        payloadSnapshot: {
          ...payload,
          challengeType: POS_DEVICE_AUTH_QR,
          storeCode: active.store.code,
          storeName: active.store.name,
          deviceName,
          approvedAt: new Date().toISOString(),
        } as Prisma.InputJsonValue,
      },
    })
    return { ok: true, storeName: active.store.name, deviceName }
  })
}

/**
 * Atomically consumes a challenge, activates the requesting browser device,
 * signs its pos-device-v1 token and writes audit events. The raw token is never
 * persisted in ordinary audit payloads; an AES-GCM encrypted, TTL-bound delivery
 * envelope is retained only for an exact idempotent replay of this bind operation.
 */
export async function redeemBrowserPosAuthorization(input: {
  requestId: string
  deviceId: string
  bindingAttemptId: string
  deviceName?: string | null
  browserInfo?: string | null
}) {
  return prisma.$transaction(async (tx): Promise<ChallengeSuccess<{
    token: string
    storeCode: string
    storeName: string
    deviceName: string
    browserDeviceId: string
    expiresAt: Date
  }> | ChallengeFailure> => {
    const row = await lockChallenge(tx, input.requestId)
    if (!row) return { ok: false, status: 404, error: 'NOT_FOUND' }

    const payload = readPayload(row.payloadSnapshot)
    const type = challengeType(payload)
    if (isExpired(payload)) return { ok: false, status: 410, error: 'CHALLENGE_EXPIRED' }

    // Opportunistically remove expired ciphertext from other operations. The
    // current row is retained and marked EXPIRED below so retries fail closed.
    const now = new Date()
    await tx.browserPosBindingDelivery.deleteMany({
      where: { expiresAt: { lt: now }, requestId: { not: input.requestId } },
    })
    const existingDelivery = await tx.browserPosBindingDelivery.findUnique({
      where: { requestId: input.requestId },
    })
    if (existingDelivery) {
      const matchesOperation =
        existingDelivery.tenantId === row.tenantId
        && existingDelivery.storeId === row.storeId
        && existingDelivery.browserDeviceId === input.deviceId
        && existingDelivery.bindingAttemptId === input.bindingAttemptId
      if (!matchesOperation) return { ok: false, status: 409, error: 'CHALLENGE_USED' }
      if (existingDelivery.status !== 'READY' || existingDelivery.expiresAt <= now) {
        if (existingDelivery.status === 'READY') {
          await tx.browserPosBindingDelivery.update({
            where: { id: existingDelivery.id },
            data: { status: 'EXPIRED', encryptedResult: '' },
          })
        }
        return { ok: false, status: 409, error: 'DELIVERY_EXPIRED' }
      }
      const context: BrowserPosBindingDeliveryContext = {
        requestId: input.requestId,
        tenantId: row.tenantId,
        storeId: row.storeId ?? '',
        browserDeviceId: input.deviceId,
        bindingAttemptId: input.bindingAttemptId,
      }
      const delivered = openBrowserPosBindingDelivery(existingDelivery.encryptedResult, context)
      if (!delivered || delivered.browserPosDeviceId !== existingDelivery.browserPosDeviceId) {
        return { ok: false, status: 409, error: 'DELIVERY_UNAVAILABLE' }
      }
      return {
        ok: true,
        token: delivered.token,
        storeCode: delivered.storeCode,
        storeName: delivered.storeName,
        deviceName: delivered.deviceName,
        browserDeviceId: delivered.browserPosDeviceId,
        expiresAt: new Date(delivered.tokenExpiresAt),
      }
    }

    if (payload.browserPosDeviceId || (row.status === 'SUCCESS' && payload.deliveredAt)) {
      return { ok: false, status: 409, error: 'CHALLENGE_USED' }
    }

    if (type === POS_DEVICE_AUTH_QR) {
      const hasLegacyApproval = row.status === 'SUCCESS' && Boolean(row.userId) && !payload.deliveredAt
      if (!payload.approvedAt && !hasLegacyApproval) return { ok: false, status: 409, error: 'CHALLENGE_NOT_APPROVED' }
      if (!row.targetId || row.targetId !== input.deviceId) return { ok: false, status: 403, error: 'CHALLENGE_TYPE_INVALID' }
    } else if (type !== POS_DEVICE_AUTH_SHARED_LINK) {
      return { ok: false, status: 409, error: 'CHALLENGE_TYPE_INVALID' }
    }

    const active = await resolveActiveStoreAndIssuer(tx, {
      tenantId: row.tenantId,
      storeId: row.storeId,
      issuerUserId: row.userId,
    })
    if (!active.ok) {
      return {
        ok: false,
        status: 403,
        error: active.error,
      }
    }

    const deviceName = cleanText(input.deviceName, 80) ?? payload.deviceName ?? '前台收银机'
    const browserInfo = cleanText(input.browserInfo, 1_000)
    // The helper signs the credential and writes the BrowserPosDevice plus its
    // audit row using *this same tx*. Any exception rolls the challenge back to
    // unconsumed, so a used link can never exist without its bound device.
    const issued = await issueBrowserPosDeviceInTransaction(tx, {
      tenantId: active.store.tenantId,
      storeId: active.store.id,
      storeCode: active.store.code,
      deviceId: input.deviceId,
      issuedByUserId: active.issuerUserId,
      displayName: deviceName,
      browserInfo,
    })
    const deliveryExpiry = deliveryExpiresAt(payload)
    const deliveryContext: BrowserPosBindingDeliveryContext = {
      requestId: input.requestId,
      tenantId: active.store.tenantId,
      storeId: active.store.id,
      browserDeviceId: input.deviceId,
      bindingAttemptId: input.bindingAttemptId,
    }
    const encryptedResult = sealBrowserPosBindingDelivery({
      ...deliveryContext,
      browserPosDeviceId: issued.device.id,
      token: issued.token,
      storeCode: active.store.code,
      storeName: active.store.name,
      deviceName,
      tokenExpiresAt: issued.expiresAt.toISOString(),
    })
    await tx.browserPosBindingDelivery.create({
      data: {
        ...deliveryContext,
        browserPosDeviceId: issued.device.id,
        encryptedResult,
        expiresAt: deliveryExpiry,
      },
    })
    const deliveredAt = new Date().toISOString()
    await tx.operationLog.update({
      where: { id: row.id },
      data: {
        targetId: input.deviceId,
        userId: active.issuerUserId,
        status: 'SUCCESS',
        message: type === POS_DEVICE_AUTH_SHARED_LINK
          ? 'Browser POS shared link redeemed and device bound'
          : 'Browser POS authorization redeemed by requesting browser',
        payloadSnapshot: {
          ...payload,
          challengeType: type,
          storeCode: active.store.code,
          storeName: active.store.name,
          deviceName,
          browserInfo,
          deliveredAt,
          boundAt: deliveredAt,
          browserPosDeviceId: issued.device.id,
          tokenExpiresAt: issued.expiresAt.toISOString(),
        } as Prisma.InputJsonValue,
      },
    })
    await tx.operationLog.create({
      data: {
        tenantId: active.store.tenantId,
        storeId: active.store.id,
        userId: active.issuerUserId,
        actionType: type === POS_DEVICE_AUTH_SHARED_LINK
          ? 'BROWSER_POS_SHARED_LINK_REDEEMED'
          : 'BROWSER_POS_QR_AUTH_REDEEMED',
        targetType: 'BROWSER_POS_DEVICE',
        targetId: issued.device.id,
        requestId: row.requestId,
        status: 'SUCCESS',
        payloadSnapshot: {
          browserDeviceId: input.deviceId,
          bindingAttemptId: input.bindingAttemptId,
          deviceName,
          tokenExpiresAt: issued.expiresAt.toISOString(),
        },
      },
    })
    return {
      ok: true,
      token: issued.token,
      storeCode: active.store.code,
      storeName: active.store.name,
      deviceName,
      browserDeviceId: issued.device.id,
      expiresAt: issued.expiresAt,
    }
  })
}

export function getPosAuthorizationPayload(value: unknown) {
  return readPayload(value)
}

export function getPosAuthorizationChallengeType(value: unknown) {
  return challengeType(readPayload(value))
}

export function isPosAuthorizationExpired(value: unknown) {
  return isExpired(readPayload(value))
}
