import { BrowserWindow } from 'electron'

let bindingWindow: BrowserWindow | null = null

function page(message?: string) {
  const error = message ? `<p class="error">${message.replace(/[<>&"]/g, '')}</p>` : ''
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; form-action https://e-shop-tray-field.invalid"><meta name="viewport" content="width=device-width,initial-scale=1"><title>E-Shop Tray FIELD</title><style>body{font-family:Segoe UI,sans-serif;background:#f7f8fa;color:#172033;margin:0;padding:28px}.card{background:#fff;border-radius:18px;padding:24px;box-shadow:0 12px 40px #0002}.mark{width:42px;height:42px;border-radius:12px;background:#2563eb;color:#fff;display:grid;place-items:center;font-weight:800;margin-bottom:14px}h1{font-size:21px;margin:0 0 7px}p{font-size:13px;line-height:1.5;color:#5b6474}.store{font-weight:700;color:#172033}label{display:block;font-size:13px;font-weight:700;margin:20px 0 7px}input{box-sizing:border-box;width:100%;font-size:24px;letter-spacing:6px;padding:11px 13px;border:1px solid #ccd2dc;border-radius:11px;text-align:center}button{width:100%;margin-top:15px;border:0;border-radius:11px;background:#2563eb;color:#fff;padding:13px;font-size:14px;font-weight:700}.error{color:#b91c1c}</style></head><body><section class="card"><div class="mark">E</div><h1>Connect FIELD Store</h1><p>Cloud Relay · <span class="store">ST169E7000</span></p><p>Enter the one-time connection code generated by the Telegram OWNER.</p>${error}<form action="https://e-shop-tray-field.invalid/submit" method="get"><label for="pin">6-digit connection code</label><input id="pin" name="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" autofocus required><button type="submit">Connect</button></form></section></body></html>`
}

export function showFieldBindingWindow(onPin: (pin: string) => Promise<{ ok: true } | { ok: false; message: string }>) {
  if (bindingWindow && !bindingWindow.isDestroyed()) { bindingWindow.show(); bindingWindow.focus(); return }
  const win = new BrowserWindow({
    title: 'E-Shop Tray FIELD',
    width: 430,
    height: 520,
    resizable: false,
    maximizable: false,
    fullscreenable: false,
    autoHideMenuBar: true,
    backgroundColor: '#f7f8fa',
    webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true },
  })
  bindingWindow = win
  win.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
  win.webContents.on('will-navigate', (event, url) => {
    event.preventDefault()
    let pin = ''
    try {
      const target = new URL(url)
      if (target.hostname !== 'e-shop-tray-field.invalid' || target.pathname !== '/submit') return
      pin = target.searchParams.get('pin')?.trim() ?? ''
    } catch { return }
    if (!/^\d{6}$/.test(pin)) { void win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(page('Enter a valid 6-digit code.'))}`); return }
    void onPin(pin).then((result) => {
      if (result.ok) win.close()
      else void win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(page(result.message))}`)
    })
  })
  win.on('closed', () => { bindingWindow = null })
  void win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(page())}`)
}
