import { COPY, type ReportLang } from './copy'
import type { ProductSalesResult } from './contract'

function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!) }
export function reportPrintHtml(result: ProductSalesResult, lang: ReportLang) {
  const text = COPY[lang]
  const stores = new Map(result.stores.map((store) => [store.storeId, store]))
  const rows = result.rows.map((row) => `<tr><td>${escape(row.name)}<br><small>${escape(row.barcode)}</small></td><td>${escape(stores.get(row.storeId)?.storeName ?? '')}</td><td>${escape(row.quantity)}</td><td>${escape(row.salesAmount)} ${escape(stores.get(row.storeId)?.currencyCode ?? '')}</td><td>${escape(row.refundAmount)}</td></tr>`).join('')
  return `<html lang="${lang}"><head><meta charset="utf-8"><title>${escape(text.title)}</title><style>body{font:13px sans-serif;color:#111;margin:16px}h1{font-size:20px}p{line-height:1.5}table{border-collapse:collapse;width:100%;font-size:12px}td,th{border-bottom:1px solid #ccc;padding:6px;text-align:left;overflow-wrap:anywhere}thead{display:table-header-group}tr{break-inside:avoid}small{color:#555}@page{margin:10mm}</style></head><body><h1>${escape(result.groupName ?? text.title)}</h1><p class="meta">${escape(result.range.dateFrom)} — ${escape(result.range.dateTo)}<br>${escape(text.generated)}: ${escape(new Date(result.generatedAt).toLocaleString(lang, { timeZone: result.range.timezone }))}</p><p>${escape(text.rule)}</p><p>${escape(text.moneyNote)}</p>${result.unidentifiedSales ? `<p>${escape(text.incomplete)}</p>` : ''}${result.unidentifiedRefunds ? `<p>${escape(text.refundIncomplete)}</p>` : ''}<table><thead><tr>${[text.product, text.store, text.quantity, text.amount, text.refund].map((label) => `<th>${escape(label)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><h2>${escape(text.totals)}</h2>${result.totals.map((total) => `<p class="total-row">${escape(total.currencyCode)} · ${escape(text.quantity)} ${escape(total.quantity)} · ${escape(text.amount)} <strong class="total-value">${escape(total.salesAmount)}</strong> · ${escape(text.refund)} ${escape(total.refundAmount)}</p>`).join('')}</body></html>`
}
