export const CASHIER_REALTIME_OBSERVATION = {
  title: 'Cashier Realtime 成本优化观察',
  status: 'COMPLETED',
  start: '2026-08-23',
  plannedEnd: '2026-08-30',
  window: '7 Days',
  result: 'ADJUST',
  issue: 'Durable Object WebSocket close-code lifecycle exception',
  issueSeverity: 'LOW',
  adjustment: '1005 / 1006 / 1015 reserved close-code guard',
  postFixVerification: 'PASS',
  decision: 'KEEP',
  releaseStatus: 'FIELD VERIFIED / CLOSED',
  finalFrozen: true,
  productionStatus: [
    { label: 'Production Realtime', value: 'ENABLED' },
    { label: 'Production Observation', value: 'COMPLETED' },
    { label: 'Core Realtime Loop', value: 'FIELD VERIFIED' },
    { label: 'Normal Reconciliation', value: '≈30s' },
    { label: 'Failure Fallback', value: 'FIELD VERIFIED' },
    { label: 'Failure Fallback Timing', value: '≈5s' },
    { label: 'Fixed Poll Reduction', value: '≈83.3%' },
    { label: 'Fluid Active CPU', value: 'IMPROVING' },
    { label: 'Fast Origin Transfer', value: 'IMPROVING' },
    { label: 'Business Regression', value: 'NONE FOUND' },
  ],
  baseline: [
    { metric: 'Cashier 固定轮询', before: '≈5s', current: '≈30s' },
    { metric: '单 API 固定请求', before: '≈12/min', current: '≈2/min' },
    { metric: '两 API 固定请求合计', before: '≈24/min', current: '≈4/min' },
    { metric: '固定轮询下降', before: '—', current: '≈83.3%' },
  ],
  safety: [
    { label: 'Cloudflare required for business correctness', value: 'NO' },
    { label: 'Gateway failure behavior', value: 'DEGRADED → existing ≈5s polling' },
    { label: 'Reconnect', value: 'Immediate Pull → HEALTHY' },
    { label: 'Duplicate WebSocket', value: 'NONE OBSERVED' },
    { label: 'Request Storm', value: 'NONE OBSERVED' },
    { label: 'Business Regression', value: 'NONE FOUND' },
    { label: 'Cloudflare Bugfix Production', value: 'PASS' },
    { label: 'Post-fix hibernation event', value: 'SUCCESS' },
    { label: 'New scriptThrewException', value: '0' },
    { label: 'New same-signature 1005 exception', value: '0' },
    { label: 'Customer Display', value: 'UNAFFECTED' },
    { label: 'Database / Migration', value: 'NONE' },
  ],
  checkpoints: [
    { label: 'T+24h', date: '2026-08-24', status: 'NOT RECORDED' },
    { label: 'T+72h', date: '2026-08-26', status: 'NOT RECORDED' },
    { label: 'T+7d', date: '2026-08-30', status: 'ADJUST' },
  ],
} as const
