export const CASHIER_REALTIME_OBSERVATION = {
  title: 'Cashier Realtime 成本优化观察',
  status: 'OBSERVING',
  start: '2026-08-23',
  plannedEnd: '2026-08-30',
  window: '7 Days',
  productionStatus: [
    { label: 'Production Realtime', value: 'ENABLED' },
    { label: 'Core Realtime Loop', value: 'FIELD VERIFIED' },
    { label: 'Normal Reconciliation', value: '≈30s' },
    { label: 'Failure Fallback', value: '≈5s' },
    { label: 'Failure Fallback Field Verify', value: 'PASS' },
  ],
  baseline: [
    { metric: 'Cashier 固定轮询', before: '≈5s', current: '≈30s' },
    { metric: '单 API 固定请求', before: '≈12/min', current: '≈2/min' },
    { metric: '两 API 固定请求合计', before: '≈24/min', current: '≈4/min' },
    { metric: '固定轮询下降', before: '—', current: '≈83.3%' },
  ],
  safety: [
    { label: 'Cloudflare required for business correctness', value: 'NO' },
    { label: 'Gateway failure behavior', value: 'DEGRADED → existing ≈5s polling' },
    { label: 'Reconnect', value: 'Immediate Pull → HEALTHY' },
    { label: 'Duplicate WebSocket', value: 'NONE OBSERVED' },
    { label: 'Request Storm', value: 'NONE OBSERVED' },
    { label: 'Business Regression', value: 'NONE OBSERVED' },
    { label: 'Customer Display', value: 'UNAFFECTED' },
    { label: 'Database / Migration', value: 'NONE' },
  ],
  checkpoints: [
    { label: 'T+24h', date: '2026-08-24', status: 'PENDING' },
    { label: 'T+72h', date: '2026-08-26', status: 'PENDING' },
    { label: 'T+7d', date: '2026-08-30', status: 'PENDING' },
  ],
  reviewItems: [
    '商户是否出现订单刷新异常',
    '是否出现明显新订单延迟',
    'Cloudflare Gateway 是否频繁 DEGRADED / reconnect',
    'Cashier requests 是否保持明显低于旧 5 秒模式',
    'Fluid Active CPU 是否出现改善趋势',
    'Fast Origin Transfer 是否出现改善趋势',
  ],
  plannedDecisions: ['KEEP', 'ADJUST', 'ROLLBACK', 'FINAL FROZEN'],
  decision: 'PENDING',
} as const
